version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: pg-pokemon-jackpot
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemon_jackpot_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgres/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka-pokemon-jackpot
    ports:
      - "9092:9092"
  
  redis:
    image: redis:latest
    container_name: redis-pokemon-jackpot
    restart: always
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
volumes:
  postgres-data: