version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: pg-pokemon-jackpot
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemon_jackpot_db
      DATABASE_URL: postgres://postgres:postgres@db:5432?sslmode=disable
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgres/data
volumes:
  postgres-data: